name: exomachina
channels:
  - pytorch
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - blas=1.0
  - bokeh=2.4.3
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - freetype=2.10.4
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - jinja2=3.0.3
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.3
  - libpng=1.6.37
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openssl=1.1.1q
  - packaging=21.3
  - pillow=9.2.0
  - pip=22.2.2
  - pyparsing=3.0.9
  - python=3.8.13
  - pytorch=1.4.0
  - readline=8.1.2
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.3
  - tk=8.6.12
  - torchvision=0.5.0
  - tornado=6.2
  - typing_extensions=4.3.0
  - wheel=0.37.1
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - ads==0.12.3
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - annoy==1.17.1
    - anyio==3.6.2
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.8
    - async-timeout==4.0.2
    - attrs==22.1.0
    - backcall==0.2.0
    - bcrypt==4.0.1
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - blis==0.7.9
    - bs4==0.0.1
    - catalogue==2.0.8
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==7.1.2
    - colorama==0.4.5
    - confection==0.0.3
    - conllu==4.5.2
    - contourpy==1.0.5
    - cryptography==38.0.1
    - cycler==0.11.0
    - cymem==2.0.7
    - datasets==2.6.1
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.5.1
    - en-core-sci-sm==0.4.0
    - entrypoints==0.4
    - executing==1.1.1
    - fastapi==0.85.1
    - fastjsonschema==2.16.2
    - ffmpy==0.3.0
    - filelock==3.8.0
    - fonttools==4.37.4
    - frozenlist==1.3.1
    - fsspec==2022.10.0
    - gradio==3.6
    - greenlet==1.1.3.post0
    - h11==0.12.0
    - httpcore==0.15.0
    - httpretty==0.8.10
    - httpx==0.23.0
    - huggingface-hub==0.10.1
    - idna==3.4
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - ipykernel==6.16.1
    - ipython==8.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - joblib==1.2.0
    - jsonschema==4.16.0
    - jupyter==1.0.0
    - jupyter-client==7.4.3
    - jupyter-console==6.4.4
    - jupyter-core==4.11.2
    - jupyter-server==1.21.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - linkify-it-py==1.0.3
    - markdown-it-py==2.1.0
    - matplotlib==3.6.1
    - matplotlib-inline==0.1.6
    - mdit-py-plugins==0.3.1
    - mdurl==0.1.2
    - mistune==2.0.4
    - mock==4.0.3
    - multidict==6.0.2
    - multiprocess==0.70.13
    - murmurhash==1.0.9
    - nbclassic==0.4.5
    - nbclient==0.7.0
    - nbconvert==7.2.2
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - nmslib==2.1.1
    - notebook==6.5.1
    - notebook-shim==0.2.0
    - orjson==3.8.0
    - pandas==1.5.1
    - pandocfilters==1.5.0
    - paramiko==2.11.0
    - parso==0.8.3
    - pathy==0.6.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - preshed==3.0.8
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.31
    - protobuf==3.19.0
    - psutil==5.9.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==9.0.0
    - pybind11==2.6.1
    - pycparser==2.21
    - pycryptodome==3.15.0
    - pydantic==1.8.2
    - pydub==0.25.1
    - pygments==2.13.0
    - pynacl==1.5.0
    - pyrsistent==0.18.1
    - pysbd==0.3.4
    - python-dateutil==2.8.2
    - python-multipart==0.0.5
    - pytz==2022.5
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qtconsole==5.3.2
    - qtpy==2.2.1
    - regex==2022.9.13
    - requests==2.28.1
    - responses==0.18.0
    - rfc3986==1.5.0
    - sacremoses==0.0.53
    - scikit-learn==1.1.2
    - scipy==1.9.3
    - scispacy==0.5.1
    - send2trash==1.8.0
    - sentencepiece==0.1.91
    - smart-open==5.2.1
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - spacy==3.0.8
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - sqlalchemy==1.4.42
    - sqlalchemy-utils==0.38.3
    - srsly==2.4.5
    - stack-data==0.5.1
    - starlette==0.20.4
    - terminado==0.16.0
    - thinc==8.0.17
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tokenizers==0.9.3
    - tqdm==4.64.1
    - traitlets==5.5.0
    - transformers==3.5.0
    - typer==0.3.2
    - typing-extensions==4.4.0
    - uc-micro-py==1.0.1
    - urllib3==1.26.12
    - uvicorn==0.19.0
    - wasabi==0.10.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - websockets==10.3
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - wordcloud==1.8.2.2
    - xxhash==3.1.0
    - yarl==1.8.1
    - zipp==3.10.0
