name: exomachina
channels:
  - pytorch
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=38.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - ffmpeg=4.3
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.4.7
  - jupyter_console=6.4.3
  - jupyter_core=4.11.2
  - jupyter_server=1.18.1
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.15.2
  - jupyterlab_widgets=1.0.0
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libclang=12.0.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libffi=3.3
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm12=12.0.0
  - libpng=1.6.37
  - libpq=12.9
  - libsodium=1.0.18
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvm-openmp=14.0.6
  - lxml=4.9.1
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.5.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openh264=2.1.1
  - openssl=1.1.1s
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytorch=1.13.0
  - pytz=2022.1
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - send2trash=1.8.0
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.3
  - stack_data=0.2.0
  - terminado=0.13.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - tornado=6.2
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022f
  - urllib3=1.26.12
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - accelerate==0.14.0
    - filelock==3.8.0
    - greenlet==2.0.1
    - huggingface-hub==0.11.0
    - psutil==5.9.4
    - pyyaml==6.0
    - regex==2022.10.31
    - sqlalchemy==1.4.44
    - sqlalchemy-utils==0.38.3
    - tokenizers==0.13.2
    - tqdm==4.64.1
    - transformers==4.24.0
